node_id=2
node_name='standby'
conninfo='host=163.61.156.112 user=repmgr dbname=repmgr connect_timeout=2'
data_directory='/var/lib/postgresql/16/main'
failover=automatic
promote_command='/usr/bin/repmgr standby promote -f /etc/repmgr.conf --log-to-file'
follow_command='/usr/bin/repmgr standby follow -f /etc/repmgr.conf --log-to-file --upstream-node-id=%n'
monitoring_history=yes
reconnect_attempts=6
reconnect_interval=10
# Reconfigure PgBouncer on VM-1 after promotion
event_notification_command='/usr/local/bin/failover_pgbouncer.sh %n %e'
