# PostgreSQL Client Authentication Configuration
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
local   all             postgres                                peer
local   all             all                                     md5
local   repmgr          repmgr                                  trust
local   replication     repmgr                                  trust

# IPv4 connections - Application and Replication
host    all             all             127.0.0.1/32            md5
host    laravel_app     laravel_db      163.61.156.56/32        md5
host    repmgr          repmgr          163.61.156.0/24         md5
host    replication     repmgr          163.61.156.0/24         md5
